### ISSUE TITLE
All Pages, check error script or inconsistent html tag also remove old watermark

### ISSUE THREAD

**Issue by softwaredev28** [m2k6artworks/e-course#11]
Informasi dari konten yang disajikan pada web, bahasanya tidak konsisten. Dibuat standarisasi pakai bahasa inggris aja

**Comment by m2k6artworks** [comment]
Bantu check di setiap halaman jika ada error javascript atau tag html yang tidak consistent sesuai best practice. Serta hapus watermark lama di bagian footer
